### ISSUE TITLE
Copying example code / License File

### ISSUE THREAD

**Issue by Janno** [ybertot/plugin_tutorials#7]
Hey Yves,
Thanks so much for putting together these tutorials. I was very happy to find a concise example of how to declare `Definition`s in OCaml. My only question is: am I allowed to copy this code for my own plugins? I couldn't find a license file so I didn't know what to assume. It would be great if you could clarify that.

Thanks!

**Comment by ybertot** [comment]
Thanks, I will try to act on this this afternoon.  I intend this to be placed under a simple licence.  Would LGPL-2.1 (the same as Coq code) be the right answer?

Another solution would be to put it in some form of CC.

Yves

**Comment by ybertot** [comment]
The repository now has the same license as the Coq development.

**Comment by Zimmi48** [comment]
>Thanks, I will try to act on this this afternoon. I intend this to be placed under a simple licence. Would LGPL-2.1 (the same as Coq code) be the right answer?

It seems overkill. By choosing LGPL, you are forcing any new plugin starting from this code to use the same license. Even the FSF (the authors of the license) do not recommend it for such short works: 

>It is not worth the trouble to use copyleft for most small programs. We use 300 lines as our benchmark: when a software package's source code is shorter than that, the benefits provided by copyleft are usually too small to justify the inconvenience of making sure a copy of the license always accompanies the software.

(from https://www.gnu.org/licenses/license-recommendations.html)

Given how useful it would be for people to be able to copy this code without having to consider the licensing implications *at all*, I recommend public domain, i.e. either CC0 (https://creativecommons.org/choose/zero/) or The Unlicense which is one of those recommended by GitHub (https://choosealicense.com/licenses/#unlicense).
