### ISSUE TITLE
Please, create 8.8, 8.9 branches; it does not work with `master`.

### ISSUE THREAD

**Issue by ejgallego** [ybertot/plugin_tutorials#9]
Please, create proper branches for the tutorial.

Also, current code doesn't work with Coq's `master`.

This is prerequisite to get https://github.com/coq/coq/pull/8531 in Coq, which should enable us to keep this tutorial updated.

**Comment by ejgallego** [comment]
As to unblock this, maybe we should move this repository to the Coq org ?

**Comment by ybertot** [comment]
I am sorry, I was busy on other topics and will look into it this week.  But I am not sure to solve the problems.

**Comment by ybertot** [comment]
I think I did what was requested.
- there are now a coq-8.8 and a coq-8.9 branch
The tip of master compiles with today's coq master without error or warning.

**Comment by ybertot** [comment]
I should have added that, as far as I know, the branches coq-8.8 and coq-8.9 compile with the announced version of Coq.

**Comment by ejgallego** [comment]
Great, thanks @ybertot , will check the CI works and close this issue.

A nit comment: maybe you could consider naming the branches `v8.8` and `v8.9` , we will propose CI developments that can to follow the same branch naming convention than Coq so we can use a "convention over configuration" style.

Also, in the past @Zimmi48 mentioned that maybe this tutorial is important enough as to be moved to the Coq organization, will let you folks thing about that.

**Comment by Zimmi48** [comment]
I think that if a convention must be chosen, having the branch named `coq-8.8` and `coq-8.9` is actually better (because clearer) than `v8.8` and `v8.9`.

**Comment by Zimmi48** [comment]
>Also, in the past @Zimmi48 mentioned that maybe this tutorial is important enough as to be moved to the Coq organization, will let you folks thing about that.

I didn't say move to the Coq organization, I said move to the Coq repository itself. There are many plugins in the Coq repository that people look into when they want to create their own (but they do not follow best practices to say the least). Having special example plugins there would serve them better and would encourage developers to update these examples. Just transferring the repository to the coq organization would be pretty useless I believe (repository in github.com/coq which are not coq/coq tend to go unmaintained :disappointed:).

**Comment by ejgallego** [comment]
Interesting, so would you support renaming the coq branches to `coq-v8.8` ?

IMHO it is very important for convention to work to use the exact naming.

**Comment by ejgallego** [comment]
The plugins compiles now on my CI branch, thanks @ybertot !

**Comment by Zimmi48** [comment]
>Interesting, so would you support renaming the coq branches to coq-v8.8 ?

Certainly not. I'm talking about the branch name of external plugins, not of Coq itself.

**Comment by ejgallego** [comment]
> Certainly not. I'm talking about the branch name of external plugins, not of Coq itself.

Then I don't like that naming proposal. The whole point of same-branch naming is indeed to remove any transformation between branch names.

**Comment by ybertot** [comment]
I support @Zimmi48 's proposal of using a different name from the one in the coq repository.  An external plugin might want to use its own version and branches and v8.8 is too anonymous to be reserved just to track the coq system.  On the other hand, a tag of the form coq-8.8 means exactly what I want: whatever my own version is this tag is supposed to follow version 8.8 of coq.

In the case of plugin_tutorial, this question is rather useless, though.

**Comment by ejgallego** [comment]
> In the case of plugin_tutorial, this question is rather useless, though.

Indeed the case is that for most Coq plugins the question is rather useless, so that's the point of proposing the convention. The versioning of plugin is 100% tied to the particular version of Coq, in the large majority of cases. Thus it makes sense to have versions numbers such as `v8.9+0.2.1` etc...
